# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Patxi Andueza Rodrigo
title: Ingeniero en Tecnologías de Telecomunicación
email: PAnduezaRodrigo@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username: PatxiAndueza
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: patxi-andueza-rodrigo-b73320229
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: Sobre mí
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs

  Esto es una plantilla que haré en algún momento, no soy Brett...
  
  
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Estudios # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad Pública de Navarra
        caption: 2016 - 2022
        sub_title: Grado en Ingeniería en Tecnologías de Telecomunicación
        quote: >
           El Grado en Ingeniería en Tecnologías de Telecomunicación de la UPNA cuenta con el sello de calidad Eurace, EUR-ACE®. El sello EUR-ACE es una acreditación que busca diferenciar a los mejores centros donde se imparten ingenierías.
        description: | # this will include new lines to allow paragraphs
          
          Durante mi tiempo en la universidad aprendí, muchas de las habilidades que me acompañan en mi carrera profesional, como el trabajo en equipo y trabajar con plazos ajustados de tiempos.
          
          Al especializarme en la mención de telemática salí con un gran abanico de conocimientos de <mark>*Networking*</mark> y de programación <mark>*full stack.*</mark> 

          Además, obtuve Matrícula de Honor en la asignatura *DSCR*, demostrando mi dominio sobre <mark>Java</mark> y <mark>Android Studio.</mark>
          
      - layout: left
          title: IES Mendillorri BHI
          caption: 2014 - 2016
          sub_title: Bachiller en la modalidad de Ciencias y Tecnología          
          description: | # this will include new lines to allow paragraphs

           Durante esta época, no solo desarrolle mi gusto por las ciencias y las matematicas (incluso me presente a las Olimpiadas Matemáticas), si no que también aprendí a <mark> hablar y hacer presentaciones en público </mark> (¡desarrollé tanto esta faceta que termine presentando la graduación del curso!)


  - title: Un Poco Más Sobre Mí
    layout: text
    content: | # this will include new lines to allow paragraphs
      Ademas de mis intereses en *netwoks* e *ingenieria software* algunos de mis intereses son:
      - Todo lo que tenga una narrativa, series, películas, audiodramas...
      - La industria del videojuego
      - Salir a pasear acompañado de un buen podcast

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
